app:
  theme: "default"
  verify_version: true
  emoji: false
  terminal_colorful: false
  run_time_app: 1
  monitor_to_use: 1
  multi_account:
    enable: false
    window_title: "sunflower land"
    window_fullscreen: false


threshold:
  default: 0.7

services:
  telegram: false

log:
  save_to_file: false
  console: false
  show_print: false
